### ISSUE TITLE
How to reproduce the same kind of results as stated in the illustrations ?

### ISSUE THREAD

**Issue by arunumd** [DrawZeroPoint/hope#1]
According to the repository, the objects belonging to different horizontal planes are colored with different colors and there is a clear differentiation between them like it is shown below :
![expected](https://user-images.githubusercontent.com/32076623/83930728-0379b780-a767-11ea-8c12-0e472cbb2108.png)

I am trying to reproduce the same kind of results with a scene point cloud like this one below :
![Original_scene](https://user-images.githubusercontent.com/32076623/83930733-0a082f00-a767-11ea-8fcf-b4796d378131.png)

However, in my HoPE visualization I don't see such kind of clear differentiation in the colors (please see the image below) like that of the first illustration.
![HoPE_result](https://user-images.githubusercontent.com/32076623/83930738-0f657980-a767-11ea-9a5d-799cd4d46f06.png)

Can you please let me know how to get the same kind of results ?

**Comment by DrawZeroPoint** [comment]
Hi @arunumd 
I assume the problem is that the given point cloud's coordinates were not pre-aligned. From what I saw in the last figure given, the z-axis in the scene should have been perpendicular to all horizontal planes within the scene. And if that is the case, you can simply rotate the point cloud with CloudCompare or MeshLab beforehand, letting the z-axis pointing in the right direction.

You can also run a quick example to check the setup as detailed in README:

```
roscore

# assume hope is located at /home/USER
cd ~/hope/build/devel/lib/hope

./hope_node ~/hope/example/ 1305031459.259760.png 1305031459.274941.png -0.2171 -0.0799 1.3959 -0.8445 -0.0451 0.0954 0.5251 

```

The expected visualization should like this (notice the relative pose of the coordinate frame at the bottom right corner with those planes):

![Screenshot from 2020-06-06 16-39-25](https://user-images.githubusercontent.com/9150346/83940059-565d7880-a814-11ea-9ab4-d81593b5fbe0.png)

Note that the total number of detected plane patches is logged into the console, where for this example, it is 13 under default coefficients. If the number is 0, then no plane was detected and the colorization would not take effect.

**Comment by arunumd** [comment]
Thanks. Also do you have a suggested way I can use HoPE for horizontal plane detection with a rosbag with only the sensor_msgs::PointCloud2 topic ? I tried to run the ros node and the rosbag simultaneously. But the PointCloud was not getting recognized by the ros node
